apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: cloudflare-bundle
spec:
  sources:
  - useDefaultCAs: true
  - secret:
      name: "wildcard-tls"
      key: "ca.crt"
  target:
    configMap:
      key: "trust-bundle.pem"
