apiVersion: v1
kind: Secret
metadata:
    name: postgres-app-credentials
    namespace: data
type: kubernetes.io/basic-auth
stringData:
    userame: ENC[AES256_GCM,data:C6MYDikDAA==,iv:hIgd1DnMi4UUc1+DOeEfmPFtTUio0hH0+sqq57BUJmw=,tag:34/kDiYdBzP5zkgT/OY6cg==,type:str]
    password: ENC[AES256_GCM,data:BwqH+6e3dJtanfmeksJzAfT6khxy,iv:1OHlD9eF+HVUj4rv1FyfgeXL2jSApBdn2GwPOESNv1c=,tag:O538wKoIf2PuY3MPV9AK0A==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-02T02:11:56Z"
    mac: ENC[AES256_GCM,data:Z2txS3BzJJ8nPLA+lqGKyEACJPbcYIbCRL3RS4MhhZXATDiqBRDQ/C1pbo7rdYzPHGE++NSUMO24Yt5Pf80kijdai5omAyNnPW5cVoAzYSqL0Qg6pEYWIymVLcluNzK+uGNc1bz5hNcacyM5Mlgs9A9hv7aeamjMUbRIAjZHZxI=,iv:a8eWgxptkASl+DhUBxWPVEUqy9UipbZB1X6STueIVDA=,tag:Ek6Jcu8OvU2z8LvRExw9ww==,type:str]
    pgp:
        - created_at: "2026-08-02T02:11:56Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwQgRRSI4paOAQ//fla22YFzUp6M0MC9ZCn5OaPiA+8ylhxDuOZWv//SXdOd
            mr3pE+n4DBkeCnwukYfhqyCxU8zLGe0a8RyrPV6IepJ2NmsTH+D7rF/Irul9P7Cz
            LqbDlYzvR6QH3bzm3iuDtD1emwpNib/qBcf0mUkRX6rjla/LTs8rhMC1ALg1EF52
            ppHQHkmmw4Nv4xeRDw/zvZnnvnRTXhHWikuv/3kTbQiyhohvWAeX2Kb9S/cFX/Fq
            xxMREf2DAEZiEqRGHZ1kIbufhMDkO333CWlMJubf3ywqSVteoy3SLpkUgyAZYu5m
            ioY45ohwhibfOo/1/wtVQo8Ai0MH8sBM0THrMoVO+1kTySiseekvCbEF5ocOhrDA
            /6hykBJCQJJWJF5w6LtcTqtDZLwAYvtnMCvVOho5iTRYNhn94Y0UM2DjxE+1tlXH
            D2xmGy+JxVRY3nbLZvvK+Y1Cuw5sqep6y3oa63wRgBghoy64R9+0PgLwQqqGe26v
            iEigCSvKwwviBFoa8f5PiPKpuohrXZimdnLVsBrvEV8ujt2ulzvKVYOL0ea19Cla
            K3JHnv2II+xob6FaFcykikB36BlbnI1M9RP5p+ktlIdPBkGRkkXaRT4B1QHAsqM1
            BzP4lScnep9gPDgPo324+3Ob2GDYeRC+h1h8Y1mO4jqM170EbOhmFoDmV3fKVP7S
            XAGpD4thkaE3PEqCEDcLUMtRjgFknJUqP2PSQjAmU8zl1zWDeGaZtW2TrQJRhzY9
            m4vlJVuRG4ts1NzYz6Fg3umPM9tu6NT0JfmX1imyqEeu/ECcU4SaHwkRKILG
            =75eV
            -----END PGP MESSAGE-----
          fp: E7D18B4BC10A415DC6CAC35D49050A20B365DB0D
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres-superuser-secret
    namespace: data
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:JmQYgkho4Yc=,iv:LMKVNYS4sQdzoEqCDW5zP1nl6H2pRDWBMHT6awy6xF8=,tag:Hiw6o89bDhqu5eXOy2gLpw==,type:str]
    password: ENC[AES256_GCM,data:uz5RgF2AjThtfugmIc0P,iv:/AKkTCaOAk58UlW4ifS5GESIiL7bzF5qhpIzrcUGO70=,tag:KvfuKOfFhR0OZOxoufsQhA==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-02T02:11:56Z"
    mac: ENC[AES256_GCM,data:Z2txS3BzJJ8nPLA+lqGKyEACJPbcYIbCRL3RS4MhhZXATDiqBRDQ/C1pbo7rdYzPHGE++NSUMO24Yt5Pf80kijdai5omAyNnPW5cVoAzYSqL0Qg6pEYWIymVLcluNzK+uGNc1bz5hNcacyM5Mlgs9A9hv7aeamjMUbRIAjZHZxI=,iv:a8eWgxptkASl+DhUBxWPVEUqy9UipbZB1X6STueIVDA=,tag:Ek6Jcu8OvU2z8LvRExw9ww==,type:str]
    pgp:
        - created_at: "2026-08-02T02:11:56Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwQgRRSI4paOAQ//fla22YFzUp6M0MC9ZCn5OaPiA+8ylhxDuOZWv//SXdOd
            mr3pE+n4DBkeCnwukYfhqyCxU8zLGe0a8RyrPV6IepJ2NmsTH+D7rF/Irul9P7Cz
            LqbDlYzvR6QH3bzm3iuDtD1emwpNib/qBcf0mUkRX6rjla/LTs8rhMC1ALg1EF52
            ppHQHkmmw4Nv4xeRDw/zvZnnvnRTXhHWikuv/3kTbQiyhohvWAeX2Kb9S/cFX/Fq
            xxMREf2DAEZiEqRGHZ1kIbufhMDkO333CWlMJubf3ywqSVteoy3SLpkUgyAZYu5m
            ioY45ohwhibfOo/1/wtVQo8Ai0MH8sBM0THrMoVO+1kTySiseekvCbEF5ocOhrDA
            /6hykBJCQJJWJF5w6LtcTqtDZLwAYvtnMCvVOho5iTRYNhn94Y0UM2DjxE+1tlXH
            D2xmGy+JxVRY3nbLZvvK+Y1Cuw5sqep6y3oa63wRgBghoy64R9+0PgLwQqqGe26v
            iEigCSvKwwviBFoa8f5PiPKpuohrXZimdnLVsBrvEV8ujt2ulzvKVYOL0ea19Cla
            K3JHnv2II+xob6FaFcykikB36BlbnI1M9RP5p+ktlIdPBkGRkkXaRT4B1QHAsqM1
            BzP4lScnep9gPDgPo324+3Ob2GDYeRC+h1h8Y1mO4jqM170EbOhmFoDmV3fKVP7S
            XAGpD4thkaE3PEqCEDcLUMtRjgFknJUqP2PSQjAmU8zl1zWDeGaZtW2TrQJRhzY9
            m4vlJVuRG4ts1NzYz6Fg3umPM9tu6NT0JfmX1imyqEeu/ECcU4SaHwkRKILG
            =75eV
            -----END PGP MESSAGE-----
          fp: E7D18B4BC10A415DC6CAC35D49050A20B365DB0D
    version: 3.13.2
