apiVersion: v1
kind: Secret
metadata:
    name: baserow-secret
    namespace: data
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:Q3lxJSqw9w==,iv:l8fGTdcJv8sFyZpKlq8iuvbD+i/0u20Il6gBCfgY69Q=,tag:rmee1ZjVj7irgBJKQ4uBtQ==,type:str]
    password: ENC[AES256_GCM,data:Xjm8MsJZyH+L,iv:EkZzg1JDzEGSUYPKb1dJLUesfy8nb2HOwhREXGdDXy4=,tag:fAPxxdcjRqXKUkpbCILzeA==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-05T01:19:49Z"
    mac: ENC[AES256_GCM,data:e6lLNDuU3bbNgUnymAb+N8/tb0YrFM4Hyl8do6YN6lNg3L/0Yd3DD1ZYWo6dIZ7HZCMUvTaXUe+XNd1cHYQXFu6nND9KS4M9089+ZNexY2PrD7NT9z0Ob+b1ZdwgmE3GbKnGHZ1iWP4oXJTP2XN4pnVRqcQOjbGa5+Hv6kuwqYI=,iv:Cl/yeBqxE2zBfFxxT3KMp3a+oamCUghw5WP72SlZO1I=,tag:gMRXtix7LckAdDzSfgymOA==,type:str]
    pgp:
        - created_at: "2026-06-05T01:19:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwQgRRSI4paOAQ//aPwbLiPZTvLOKqnAxi5zsITRyFDY9ODY7NcKqlFznn5u
            A82UElqMbzOHjTJ9VRgeJU1uUuWFt7n7D8Scyrp8GMTB/DSwiZqDB4A1TFBmGxCe
            ETch9Vn/Q3GbsLJhsqZ1NSS5TKv+2WQit/vAEBAHFXIPWRCOeHvfHfuTsdUBDqJp
            3+YATp95OvJgDbayuC84tep7/rI0uoEt474SsEs0bUBRfEMy9sjfsrGJ1Q9kU6EW
            YQ2MIAtifNE9oS92HdwSsqYWFyibjXixZyHC5XaG8N2Dst5AG50enhl+noEFf9zg
            9GMjzESKcGzXptRRwIqi8oNLCXdZChFp1xwe7pp3Wbz6zSMAC0/4YMatvn0J+fOO
            lAf1JkmsSHtLnpT+HzSMoOFRDLgOObph10bwN22TXICQMY0OrLSKJazkfuicSsng
            PLrKYTgiQv9cL7CSuJG4/HHasoy6THkYlYeOp8oO3zz0zOXwjZozBQ5sQ+MK5JR8
            7AuIvemQ/ieF/ap6XC1vsD7XJY6TCpixzQc3e7ap3z0Fuo4/8XfVfi/4zofKsGq9
            R8/AVXNEHWLjymLlWEsIWdPMtCenoHIIcI0ATg0Oc+lotXq4QwkEPBoY6NDRfKRs
            t6aZeOSLfJOgOafXRzup33BttAZj1uR+VpSfY9+eGRsh0mXO8pzl7KcTvLChdJbS
            XgHDE/N/Sthngrpqv8auWlsS5gCX4xfO22G/wbBu/EjpH7K4Ny/TJ3ETuf3/jwjZ
            nK5hzDsDu5/D49bl8fVJuGDue/t1PXXX1JP7+xPD2dUspNX9brEwgTermiec1zQ=
            =3txn
            -----END PGP MESSAGE-----
          fp: E7D18B4BC10A415DC6CAC35D49050A20B365DB0D
    version: 3.13.1
