apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: kubernetes.io/basic-auth
stringData:
    api-token: ENC[AES256_GCM,data:KDg/H6ZeOQdfSgTibdSKQW1LDXhKRAluSe5/lHE9bNu+9XXqT1Gx43Q0q7TEJPGayVwScTM=,iv:FWAiOE9Rt0YbUXCLqpZrSH6teAoPWnypaRGSMQFeoB4=,tag:7VicysrO3QpJr/vrHj8fGw==,type:str]
sops:
    lastmodified: "2026-05-09T22:59:32Z"
    mac: ENC[AES256_GCM,data:m79VZhr5LHLY4bIElDy3J0Htate8gWMIuu+mZTNSnC4z085oY47WXZNUWNVhtEAS4bv+yDlTcT4yXEN7/PVQJenneuxT9PUXTCUCC9itre3qWkKfSGKLffaAM/DDGZOL6D7bxxBJ4YDSaCoac+lnTC/+X8CPYds90MM1flxqo78=,iv:CUjTLrkpI8Ahiuvr63BRwcwZ2LuQJrKK1DH93G9kxes=,tag:Mn7V1AMJPfsyCmmBszQGDQ==,type:str]
    pgp:
        - created_at: "2026-05-09T22:53:16Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwQgRRSI4paOAQ/+OX5Z83yMcIEfvy+rTvCo2g7L25bkP0B/Jz7IOKToEvrB
            ygwc3vtHh3OvplOzMTctsVUcYk/Ip2940TEX+wZq6REm5AQ87mh1iHDCcObVhanC
            Zzr//afD9nPg3lu2sQLGbR3Ne0msmU+W3yxFAZEcBhOeVmRlQ/tZbT12Mb+3ilr6
            2qeVBdLthTQTeqEyBJTEp8lyJcFSuuglaRraYKYfcuBtcC1/toYv6gl+uj39ZUJG
            U4+EimIXvRiaUUJYc+n9O+l/aaeB2QdBtTRXdIsYW6wqwIeVNXqyHFDtypD/OCgZ
            Os8DGGD1eanR28xXHa8TDgL7hrUvxczgDW0XGT+GiTzLAb4z5vgAKxDI/qnwOZGa
            2P/ZX7iLWkR5aPv1JxLjKnWGQppnrhtldW842gns0TFR6oLhBCUjHHy40rsJMeuv
            xyyZ8JBsCp8kd99FJeK33/yqFoKuqnq0HopdnEenSnzi5CJkQcfTJifQQrqU2GkW
            1+inrRt9ECfRNY8J6jw/B/8REoIVGUQ9/IScevPBmQAk/TYtMwbVvl3OXf2BBscg
            zJ9PDL12H6PXsE8pmPc/da3QCywa32vKQ1R/IfMVNmldK39ooHS1ijUo1zPVnbzE
            eMdKpGMapAITEhDZsEzJGinU6j5hhd59lSQGv2ZMxw5oXL2g+PAhXNAz1M8wxgXS
            XgEgoR9oP/z14sht0C5iGggsVN8ILb7xm5X+0ZGxb3hbaEsdZwcgrWCzGqgBSpdJ
            rAvQPwAW/it06A+1mjWaeM4WXVnegEGtYbA/bpaY3FAVpWMIjSji8xht+6Wnpdo=
            =qkDl
            -----END PGP MESSAGE-----
          fp: E7D18B4BC10A415DC6CAC35D49050A20B365DB0D
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
