apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel
    namespace: kube-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:Ci7sBFoUCdT9bV5v+Wd5ncAqZiCtTAYb3aCx0fxoCuCs5g4DSGZXYNvwl18lz1cKRLZt/0aOVOVWbV4VO21HMZrASKlRTgaKr4jRgpMOpcf4AQTvNTRGzCTFPzxNIGHo51prd+EazeZ1TmGWnuNBj3+Tzr6dkMeD6whzWt6HBtcpr/D/dZinr3dl3H9D2Vh1jO3wuaJuNhQZyMnhOzWoAM0XnigtOzk9R2SudJ8UNeOD0Egnc22xqw==,iv:mOmipbuIGhSf2a5tcT511fOe5hmYcIxW2+3EkreFJrg=,tag:3KM2FYfrfJDIsGcwWcLpgQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T01:34:17Z"
    mac: ENC[AES256_GCM,data:ezPzvQfw+m/EQH2UfEUF7/iBbr/5NxB7tiVUKiIihTvBC+sNf4Pr/byREmqk8SkFXcrgS0gkTF1kiZt0KLqsXGKPXRKjypNKlbpsoWd4T1MHyr2e0lNmP1q7ZFYLEFJj6uDHieMrIKwWo4yDqS8oLG6gfjbS2g7QEHjrp77wtvw=,iv:75S8FbPs5w1UEmnmSjSQgqCRJe3kPRzcwyz8ibipBhU=,tag:S5qG2oc0Le/zyVbI3v7MoQ==,type:str]
    pgp:
        - created_at: "2026-06-23T23:51:00Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwQgRRSI4paOARAA3foOUF+chrif2cpE1/RBAYlM3nl7cTf85VkbKapAeHPI
            ssS5bjFmGtZN9rj3pT8aiqUissN1+IyzUVOqB9Ie13Gmkjrz1dDm58iUtJQk14U/
            u5NK4gO13+skcg2pSU/VNkUjRvU6i3ex01mKkmXo42lA0uAuFBrtEbsaNLcriyjo
            Q8jy04oSyjp2/FncY+ACs8gCFbFYhwGx8agNkbpFvKJuqML1wggrCGjw/sYKXtNu
            PZ2MI4r5TWyMocrdJ7apWrgYhiRCCCLEVFU4gH0nOeiGsa8XiAguPTWBHSucXfwn
            qPCqr7XmQZBrReXc+qsnDjv7QdPlA52/X10VbbozmEunEhQtleNPP4peh1m+2lA4
            PVz9PkbD8YOs3U2k9HxdNnZ5mTncMdRzgZRRSBkV8tuy/OrUmYnfUtnjj5NBZTRs
            4feOX9ssJwpYLJLnU3nI81tdqcL6ZTKbIObaFRNQbgiEZUf1ZfMoy7S89qqfFtQU
            DATGGIbRf9AgYqD83kM+YJH/29AGja0Qd3JzyMh7uj8eoZYmVh0qayP3NfKA0Jxh
            CTun7tthmib0QmVlMzmr7UXRDvQojs6jOtdpsQKXU4kLeunt5znC7R6ryHAdfx5E
            VxvCM//qbthLzdguQdrJ61kAWkPweSYdQ5Qg6wsDxi6rSi2H81Z+S+KhWyUsSnrS
            XgE71xXRQcNITL1BtQvxYqHgJM9ioaCeY0Upo+jW6DaviwuSq6MGTgPuv1yfLfut
            jBd5rdxvRnOQIUo1+TDlsYDnlN0FWwQGc4Jk2afWXDJuJ+VGF2jt6RCLzgfI+U8=
            =acE/
            -----END PGP MESSAGE-----
          fp: E7D18B4BC10A415DC6CAC35D49050A20B365DB0D
    version: 3.13.1
