apiVersion: v1
kind: Secret
metadata:
    name: etcd-backup-secret
    namespace: kube-system
type: etcd.k3s.cattle.io/s3-config-secret
stringData:
    etcd-s3-bucket: ENC[AES256_GCM,data:ESfRl4Hp4oUoQhtyqgDgSbgpspI=,iv:Js65TtBsXgISXMbd1pp4i80gXTQHLjNalVZ53j0xLJU=,tag:RpbUzspCAXyZsU3tWHMMmw==,type:str]
    etcd-s3-endpoint: ENC[AES256_GCM,data:yQgegD9g1+6krzt7H7gr5iCFMM0PHXSbO76m+PIt,iv:h4B3u7qgWUJR+zvMw+1Z6L3Oz1Ry0v931QxUyRUTyZ8=,tag:Ml8Uaho8itfdydNAJdmrQg==,type:str]
    etcd-s3-access-key: ENC[AES256_GCM,data:Z/4C3IJISdo3P8xkunwHtMPPGt68NHZQ7Q==,iv:D02bwEfCiR534Ok9ZsxKzmACCudJ2BuQO6GjkqQ+l/s=,tag:vfDtzXZGvFuQdgfziPMXew==,type:str]
    etcd-s3-secret-key: ENC[AES256_GCM,data:FF50KYDsuCuUHmGqXq3ADpFzc76/EQ7xPvYeVZwL5Q==,iv:4ooZMHSOrt+ofIfOWXamRmcKLAFcZbF2ScTrokBaLLc=,tag:RN0Eq0XpGbITDX84PuRJOg==,type:str]
    etcd-s3-skip-ssl-verify: ENC[AES256_GCM,data:F8zcPyA=,iv:Zg6Gh+h+zQKU5I3bZy4qU11lYlk9l8m9DEMaBh3SPCw=,tag:JeuPZ8Zo3/lAaK9Y/hl/+g==,type:str]
    etcd-s3-retention: ENC[AES256_GCM,data:pbs=,iv:0FAYnygDqBbNQIQUKfHpCTQpTUVa6jNn3QdrsM7KXpA=,tag:7L0Z+RkgimYaj89mnr9g9A==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-16T01:42:51Z"
    mac: ENC[AES256_GCM,data:VR5RDdRsYkI0l4bP4iPjzivlup6w1nTllqdezSfgTrwy2FcqbVrvYzfKsOCA4xKuHNY8LKUING3JDv35H2sNddDDF1prRHVWaA8gpV/eYx/ZSQv4KU+DgqE7n/U6A4NbBELh4GtytqKjdYUW1BJ2yvH8Jglxdgj6sUpyp6R3EgE=,iv:kSFO+G+Z6aiOV42VpDPcQ4ACthVNI4xcPS2XyJkGdMQ=,tag:gBQm48Q2izc50rxaTRG5BQ==,type:str]
    pgp:
        - created_at: "2026-07-11T22:25:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwQgRRSI4paOAQ//YqVlU8eSjzU5NJBNUWKfQOFvuxeaAWWPBjigrZtb/RBk
            pYtqc0nwn+BHaNOm/3uqFJowkfRmJoEdZDuFHkjE7dNDPpx74DNONuawKbKsEh+f
            tTJdYP1GDww5nITwYzejXNTdxMFQLF5hM8OviVQFIWlf69C0mV6jG3SWuHzwNEAF
            DEEaitMHxPQvostj5qxnrfIvuUSHo2SOVRBHvD20oP6Bxk20Y97C8p/E1/TT/JkY
            /tstbrqZLHfsQLMNt06lyTq8cMyNX9+hxwVjXZGVG8GTQnJ5KmzD1rfBlPAJW1/s
            Na0a20kdC6ezFWach2Kj23rSfDS7g5bNi8B6eKQO1CuzZjMJu8vTVK9sJk84rdhr
            /tfIwqr+5Zi98mzH4lvn2eDqhnwnh996QtbGvWCgWnY9U8aNaBy8UYp316AEz2Ck
            b85tGjBV+KYkrKiGEHfGzC/Z8XzsepHyBsAvIRFKBpnjLAZwSJkw3XSoRkONzOeL
            O2YRg90dXGo+9Cqhkn1OiWPqaqXhF4FsJVhE78dy0FO9Eqkz4zrZLEmP0kzCXiLS
            mgFsF2kt7EDBat9bA8wKrGXmhBQ7ZXaMIl4spm3+Vu0U9EkHQo48Y28XyevVpDIx
            vd/2/PZQqcJaAi1THsGAkjtLiIrXA1kjbr7p8Xz41RxM4xbekZ6ChZEHxH17On3S
            XgGlBS43fl5Lx6xKpH3G+KjLVxj3ze8WoMbT681WjylMYBCcFNNRNbU/tq4doho2
            ZDCpZAb0fWiT0UXfx287iCVKhOv6Pg2xpk6qqQYyxnI+p7W5LJzGTIlY9+DlCCE=
            =6tlT
            -----END PGP MESSAGE-----
          fp: E7D18B4BC10A415DC6CAC35D49050A20B365DB0D
    version: 3.13.2
