apiVersion: v1
kind: Secret
metadata:
    name: garage-secrets
    namespace: garage
type: Opaque
stringData:
    rpcSecret: ENC[AES256_GCM,data:9z2bWr92lMEiisPXJcnDSIV0ff6aY5u5JbAPWK//sznYIIKXq+tuskIKBYG1e5UEX+dd0QndOGbTqC//EYjPuw==,iv:xXnzCViqHH10v4wPO7MOWFr+xrOcTM08UZQyHQ/IeIU=,tag:JSXcx/luIQDddfRk/3yO6A==,type:str]
    adminToken: ENC[AES256_GCM,data:2cQWfY5yQWjd7RqvrJZbU9hC5y+Lk1HLMhqNmcFsve2RyJM07jzMVr1KKoY=,iv:yxtpYjk+GbEMEl2MKhf7/V/XooZgU+xzW6EZoip5TaA=,tag:IDgT3mfnReOzSLyNI85E6w==,type:str]
    keyId: ENC[AES256_GCM,data:3tOZ/ZeUfZhyfYux2mAKFyCfDaKYD0LeoRI=,iv:PvklD5Vkn6koG0WqLKS6N1Huvx9Z75NfXNr7wasvL+U=,tag:BbP+uiGGd3ZAguD+wa3zRA==,type:str]
    secretkey: ENC[AES256_GCM,data:K+hIJIzavmD6xyGD75cKNn9aBG7E2q+BHOymx0lAOvf97Az6wKFR3AXJvKENvpHdnVet1N+mZgyB/XmeyQOdcQ==,iv:DWTUslChdM2e0CW4xBSXP3/+KGk5fKxGSKHNBXmTBxQ=,tag:B8VJGpt15W1hxVQjnz/8ug==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-25T16:54:18Z"
    mac: ENC[AES256_GCM,data:hO/3+yUePgn/N7fucsJrXtdqOS8c8lmgs1DwuU3TuiCEwm7y4H1DCv6Joz9nzeTTIhCpFbcKgDTfQjT6NP1FHzek2aJ7byTvY/whKsI7s233iilctO6sP4ubkdPScisxIqDk5XuDoyDXfpVC2sotK+SGe9e82xqQXEpOMCg61dw=,iv:6F/nInmR8tQW7/Bce6vTji2QPuqcOsoT77QoajzyMJw=,tag:37qihaUAlB6Jy2NX2yRdQA==,type:str]
    pgp:
        - created_at: "2026-05-25T16:54:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwQgRRSI4paOAQ/8CZjqspca24cjjO80Y/GMJUIB9EEOlW6nLWxHVa8OMnjW
            d2nur9CaX25O5XuIxT7clN0nMSJv1gcLb2kCuk84CCO5txMX9boPYXpftxQVqv0H
            hi9vYH1IREENMQcVfcIe3+UkEkV9YcSH3EwsmtJD7y7e5LeS2d1zJiHA0Yci3qo0
            mIUlrK6t83dlR/C8ezL8gC6Pu1S0CXkXvUlmuAvLDKMPRsHGluXRNXxaH4xsndJx
            MBw4CbfT01J+nc7wNlh4J8hhfE41H7AiFWGHtQgFGqRlZHiWDkoDcM6ALEc8oOD+
            NnvSwMOpxwFZQetyWawKv5YPf8d+dIt2QpsEWeeuYOgY61C6NiyXwLXbeYdsvMMm
            xEM65rZsPaZMZjelqqis9mq/HCb7CrRso9IFy7GcrqCuwd1hjXYT8UQdmhuEDMcd
            3jIjx0qvigBVKmxqhBv2jgeDKecb/OVI0SoM8oWevWaW5n4FF492/mvQAk/UYk4I
            T7Si16ZyXl/Tyl7CkOb+Gz4sJX8zOey0plznYNk4O8sJ5tcg9m6ceVvm9M1cc/iZ
            kBkgtUFhRIC45HHFe2PLyTA/SwM7jDwBNKDsgV0gK/D+YkV9X0Fax+rupQq8MpXb
            yJ8vIEMHOd7dVljqhn6FW7919Xcq0sHx0ZrsKl6faUj3t0JNcwrONQKTNg9wOIDS
            XgE07T81vNeAAbmO+3FuBhsD8TkIiLLuN2rZbk7MRJyIFjh+8RBWCy0ImclFEKjb
            idrU5g65sYLDeGFkZlKxu2O4fJ8zYV/D8IfO3rUZPIbGEj/4r9hyzh475NtroxI=
            =E1BK
            -----END PGP MESSAGE-----
          fp: E7D18B4BC10A415DC6CAC35D49050A20B365DB0D
    version: 3.13.1
