apiVersion: v1
kind: Secret
metadata:
    name: mariadb-app-credentials
    namespace: data
type: kubernetes.io/basic-auth
stringData:
    username: 
    password: 
---
apiVersion: v1
kind: Secret
metadata:
    name: mariadb-superuser-secret
    namespace: data
type: kubernetes.io/basic-auth
stringData:
    username: 
    password: 

