TokenID: tofu@pve!provisioner
Secret: 5b103487-a92e-498d-9440-0fc33b85acbc
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T16:36:37Z"
    mac: ENC[AES256_GCM,data:rn179LQ/TpvVwrL6d/aUdN2YJ0TkzHh3DngWVeBMFS0Z432gGq1kAzbwB28T4MHKvBqrSFlL/FK0+vlCt7yly0oQP9Mc0291cx5sF2T3hJhoE1PwUTdhik3anz03FhCCnCMk6rNWMaOTzUwIh86AdhLe5paxhxSXnmIM3KEJ1g4=,iv:oRbQDSWuubW/ahdYcokKO+amcAxBiZsB23Q0V7xEii0=,tag:dgkv1wUrJA6vsKjxKDKd+A==,type:str]
    pgp:
        - created_at: "2026-10-05T16:36:37Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwQgRRSI4paOAQ//ZqhG1GZgrJRgnd9BeCaSdolhocmdqDBivV+NS4O2QWGN
            iMAX6u8yQSHMAYw6Vx5AFfUwgaAdOCczvthsAJTclBaAJZe/JfUUqHFIJBFynfmw
            soFIwDDjfMapxB07TU4kSWq6yIyi3uSVf7jylnckuCirzioh3o5wQ2x1BN7rzdVi
            4rrrMoD7VOag+VSD1R9SW/yI76sApYBcrfme014VthmcWSxQ/30EnWIZ2nVHNJpH
            nTUJIB3WKk3VzR+xJrM7YnjTSy03inMT3beVG8NeqaKXcFQZNQhz2+XyV4kXjvRz
            SU4tUyniQx9+eZrlR6rm5GbrRsuxSM8b3g8/eMWDClYH531djjC7qc2KwNT1HVmV
            h3WEGW0an6+W4G81e/JknVPNbW6+0l6HTytCB6KcUoPeBMBIEA47RUZ1dl+RSafq
            md87aSWKb9XtjIJmV8OKow8bFrqsomhaPG4jeM0HVLniWn7t6QXvZwmCd1v9onsi
            dujIXi7h+q7/y9iXbKIdI4dRDySgjyygvT5hfXVL2Z4NVgDsf6J6TDt6uGcC1qZb
            n8gEUKRgsV+dZW4VuFCIT2WlULUaU+NZ6K2yW4sYrPyq0znZWnxB9XG3ZIqVib1m
            qcUfqVp98Zt292kjItSkFuo5qZjHHObCprRwm8jh02u0N+AXoSDCYjD1Ab6cp9nS
            XAFQdKxmYcskg8p57gN2rARIVdmYBOb1SzCp52Uk+l9i+9scFBWjB/n6kMiQVzOo
            9+LTXwzDfGs+t3H/c8h5bo+W2oFa8aywDi2rxtaWum0r4DQjsxw+Dkr6HqMq
            =rkrD
            -----END PGP MESSAGE-----
          fp: E7D18B4BC10A415DC6CAC35D49050A20B365DB0D
    version: 3.13.3
