apiVersion: v1
kind: Secret
metadata:
    name: redis-credentials
    namespace: flux-system
type: Opaque
stringData:
    redis-password: ENC[AES256_GCM,data:5irUfW/DvjfxUxVHVLEqKqRPK4ZJO+lVssghNRNdrq99VgmfleURp2CKcuHsQDSiQ9HV6ny9JoGZoLHCsuzIGA==,iv:jul9hpv2z2JZ+VBPewgzAJKbGQHm2KyKzU5+psnKl5o=,tag:2N8EyinDn42oC89Yj9P7uw==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-25T17:02:12Z"
    mac: ENC[AES256_GCM,data:5+FjkHGB6Qfq7IgMq/yLGxKdWROQ+L9G1y+m4ghUmsyfE7kzdQAcKLn28IEqcdwggbup3OyTBe4bUNQ9XR+XIU9DZmHTPBWOvVutWvPZEH86ZzT8fnB5PoJgOPVH8nDnBaSt300gE2RhP9pQP0n7vKcbDBmMq0CnMaTsfO6Z/uY=,iv:WMBMrixc8dCMPNose7MU0sVAoqxQU1U/sMBIJvWL0jU=,tag:QufwVmwXNz1tbmbPcustpg==,type:str]
    pgp:
        - created_at: "2026-05-25T17:02:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwQgRRSI4paOAQ/9E+FpDEWrxncrZLcu0VwhwtQWWTvLiGR7H6m9lZgc+Clo
            /izaAJvhjCa/E/s5YgBOFvQWfHEvDxllQcZfEDtEgnorAj+OnQDFYx54F1Irvbs8
            LbeQvlvFLoMZp4rtGS/qeub1v2bwE8SNxfdccr14UYas5zQ+xvfJk3ebUAb7XiJH
            frF9n4JnF9Kw0wiSTq7XvLET9o0X/yipHQ8PuNUAAPL41/d8FQE7D4qU8tdKMaNH
            8db3T6nS/VDzMcNNWyyMHHB4vEKQNFeVeLmymclHBkLDOUsdQJ+1OXBbwSI7zk00
            z7Hrt6/DxgtuY6KJKz/YziPhAM1YDKeU1xEqv4+UABn7FI2WkE4LUvBwJeOOibUT
            lP+pIR2KUkthUku5WZGUZSaAcWkAgNQzFzZjFfNkFc3wUrh3pJXsiRVt3OX/MRsw
            /UZik34zawwaLxJBRkH0/xWk6CA0Ev03dRVB9lVqIvYdPTaeakrOWMqbEtYLud0F
            Hgq1Jn9hwO8BHFqkdy9VA4HkKWuLmQL3mLQUKgC0pukZ89WUk2Hs3ickOlTRKVuI
            8bpCpxrjtblvKayT+2ukRvGnU5XInJIXLBYkr77bmZz8cgkT9AhiLjhJk7pMFHAf
            TMgsRMcBEQ7F+fTljKtAJ3oC6HgP3uSsMnkYcnyFY7q+vOCUOUYIEAx4g6N17wXS
            XgFpS7wlBaa/Aw5r+gGIN3lws89G/74KPW6rWtkCogjhSMYN5VCR/RR9ImixY3SC
            yZEzH4oYDRCMFB096PJtgNfl84axPoc6iLIV09wzBFlTINHOAfQsZnVwCeYf2Nc=
            =bCLj
            -----END PGP MESSAGE-----
          fp: E7D18B4BC10A415DC6CAC35D49050A20B365DB0D
    version: 3.13.1
