apiVersion: v1
kind: Secret
metadata:
    name: redis-credentials
    namespace: flux-system
type: Opaque
stringData:
    redis-password: ENC[AES256_GCM,data:z+GwzCnEkYjRx50XQoYTZzDoIMzC,iv:O0AFwVg7duemsomdkvbzKcl/Ttg4xQAWVH0GWNu5dwA=,tag:ceQSbDncS38x9fDZnFDH5A==,type:str]
sops:
    lastmodified: "2026-05-22T01:31:45Z"
    mac: ENC[AES256_GCM,data:7XwESDMMr8xjQAl0xDmBdyT90rEuMA0MIj5voJPpD7yvRpfqgvi5BOzTPIlR2RiZBcGiVONEvuDsHHbLIpt0KG9/Zh6Qzz7KgVHWdEXZcbE1G6HEbRpLAsjPOHbIjimcFDXfDXDRJldwC78ccoD45rhkXAK74C5dFpFQ9LJ2WYc=,iv:ox8jhkkzf3IyK7uAEeXXjpFai67o2HP1AzFUHpSo/SA=,tag:aGA57IyQERDIszLiPeVTPA==,type:str]
    pgp:
        - created_at: "2026-05-22T01:31:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwQgRRSI4paOARAAuLXSe9iHcZ98f4vTfY9XFIEp6Yst30VI9hDcVACgkyab
            HouN+513sJhI4ppajgZu5sejyxRdQWs3q8M5EPgjw89z+junJqx//+EazGxGlf3E
            C2HXv8rTumSw7zM/g90lDrq2UTnf6H+l19mc342EmdOfK7iZDJcOjBWdtsjxXhNW
            i3YAlLvMh/Ze9hrE0NohyTdmRW68fRlIQnm0YBcOwv0f/QEbmrPdlj7viahIRkW0
            +6S2nvNWkpeXq3QbF0SrjR2cOHUKLlHoCSsORlVvSBLFThR+GZtu/K9NtRUBBt1n
            CTSm3lBhPw/+SXJ1E3LsSycafiCA9VlpBec+LK2Izzk7uDtqReoMbKRjXqtRuyzp
            mmEHpm0kSayeUpy41aCRLI6ypYp73hAqJwWgpQqkgZi65J43UtYRwg12OFpdB/zD
            KMInRCPNt5t4GdV2ZSPes/auqoFaisRZeotOzr8yGNRjpj9LyfOXFoKq5Wr5qmEm
            WY9dULtMjcfz8a9Lhw3uxmRy27JmtlnXuDFd6F+wyoA+eDUYFRahvHZ6DoMSh3Dx
            J6MoBxELQh8tqEVCOOb4NX15TDVNmADni9XSuh3SnGNxatxbJQ8yAtXXBez9jgyT
            LI+GeGYcLf2/q5YB4UIvxWCEeD9tFwymHkckT+3a/MRE/eruUsN4u5TibEVsfezS
            XAG31enc0+KIA09GaYc244sCAi/T0uak52TGT7NRxtrImnHJE/RwcrvkLmwZdAtl
            4ws9ZN4+xAYRmewZk5JNygtQjlBcoZlI3rJvxBLOYVEdrPDtGJyz2mmyDVRh
            =9s/y
            -----END PGP MESSAGE-----
          fp: E7D18B4BC10A415DC6CAC35D49050A20B365DB0D
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
