apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:hnzqUkIVDVLTTht9fOKmOaw=,iv:mmMHdwezd/zR+eFUWmhGF6M+GWHlPAtsxNqJHIhaa1Y=,tag:8Izx4iGlNAtdHtqC/Qcw0A==,type:str]
    client_secret: ENC[AES256_GCM,data:Hokzyy62nMy1FEcKDMvJIn20nlQ0ZGEOzv6YIRaoz1w9nN44IuN2/TDdr06ZBvamSETaQ7Q6K2wXeELwoDeG,iv:flVz7NG9u+1q2rjTkYwWYyRW2VanwPKPgthDn9/cj5o=,tag:uzLpd5jJBjflOk3h6KtNUw==,type:str]
sops:
    lastmodified: "2026-05-01T22:34:53Z"
    mac: ENC[AES256_GCM,data:g4cEZHb9YWDDU2ktBMvjCCHyRgOunl4Vmsg/sLcYu7PMTB610yzrm7xxs+W+aWdTMmmjRr65BlAVGyVTRHCJTBp9xm8LxM08zLcl19y5qROuxlvZ4tnKQSU1AyxsGhLbI4LV7ZYm0JtZJvfy2aF9tqP8UWN51UQ3um+FgOMMG3M=,iv:RxN/27d44oq/5j7dW46VPo112PmQeeoU+LthsOgD048=,tag:2DTaOAucIPsnWnnZodeGTQ==,type:str]
    pgp:
        - created_at: "2026-05-01T22:19:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwQgRRSI4paOARAAtKWmWedEh7X59xdcu5P46lyv0yFYjLyiWnh5wT3FcCue
            e87flMHDwNLycJBfv9F5naWscpFtvLrLSaVGY4nB2+el3CrS7YYBxKNkDi1VRLZ6
            EcZfSkI2M7GQSE34UuiERAO56/1NnydPe1WGeH9wGOYMNJyAxMCoAKtJLMM/oRoo
            DhslJaZRgFUhHVSfgGIuVMUc4+mGOQWWJcbmTdYYqr7dbeQLKOi9q0MtknRoHbj7
            IT2h3MYXFAoY/fL+83jNOGJZBMfQNN1MSmDcf/Q1a18O4Gtiff3gjB6OavAeJs/q
            1Clpu85d4HFaRel/XGAXamhuo6Cdbzoas80XIDJGuSZQglD+vQgLHsrgy5f9jVOx
            E5sqyQ+jxB7VDh71OKmANI0AEVjQVE5AeCOQ7CH8M0N2eUnbqNojEQobG8zEtCl2
            bz8A4kk8fQPADwOqW6GKVTCd0W/n7/eLTZ7JKsoRnFImfmqlc+ijYEu1awEwtIGY
            jPZ4m9x7WIjkxy1UXruWB+ugaM95x86YjXOBB04jIMqZ+LVSXIqypiFrjC8V/8eO
            Pc0gsJm9beJfjBtSWaB8Qr/S+GncRK+qieJIGyaNYV2/a63b+oZzJghwjfx+zn55
            bqAnchvjJMZL7mpWQkTO0m20ccB524ONOhy0aL1GWPixftcfK8zPjg8PRoUY/aDS
            XAGopujCLOXtF15MBjEFqLytzuxfZBbORS45O3bFqbIw4oHFsNiV1oZOtSd71ezj
            Xz0/+TZ7wqoby18ARRKh+tdbflmVce6pg+378+jcguwiZtBthCAScdd8OyYi
            =BEW0
            -----END PGP MESSAGE-----
          fp: E7D18B4BC10A415DC6CAC35D49050A20B365DB0D
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
