apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:praJK4uMr6kXJGbW8OhSnjc=,iv:FaOBXxP3kw48S64YIOY9Oqdu5t/HSIpjDLzMB/wESxE=,tag:69cGVvOoCeDRN+KQvlnrUg==,type:str]
    client_secret: ENC[AES256_GCM,data:jmfgl0eMG892z/0xsdsZE/lGJZzFnflrj8uDCf7BJX0GR06XGG+9fjWUyGLIxjmaiQMls56ijP7z5FW0g6lw,iv:ojUEk6yl13Mlh5aQeEiAg6QXlg9AJ7EOyEGNecf3vTw=,tag:SzBWg4uZC55VT+uWKvXMBg==,type:str]
sops:
    lastmodified: "2026-05-01T22:56:23Z"
    mac: ENC[AES256_GCM,data:WuYLA17xK4QKWfFp/mVWhtutZeNd23aD+pvOjL5E+7kdoZeTHF6+6pAyjrvTgkIo5RCaFbY7yhlAy7M6WXOCtES2iRjuimo+WJa9USL75zgRtdjibWe1ivEFpXRUKOmc9YbiaBHpsIY0eTkipytaLQQ1bDlTrpxOPA77RIvnm+s=,iv:xrFRe5do1DtSlVlFf2nduDFnIQry0Zw8SrkCdoMEQqw=,tag:yyLtMge3D6jvQPrnSxXSSA==,type:str]
    pgp:
        - created_at: "2026-05-01T22:19:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwQgRRSI4paOARAAtKWmWedEh7X59xdcu5P46lyv0yFYjLyiWnh5wT3FcCue
            e87flMHDwNLycJBfv9F5naWscpFtvLrLSaVGY4nB2+el3CrS7YYBxKNkDi1VRLZ6
            EcZfSkI2M7GQSE34UuiERAO56/1NnydPe1WGeH9wGOYMNJyAxMCoAKtJLMM/oRoo
            DhslJaZRgFUhHVSfgGIuVMUc4+mGOQWWJcbmTdYYqr7dbeQLKOi9q0MtknRoHbj7
            IT2h3MYXFAoY/fL+83jNOGJZBMfQNN1MSmDcf/Q1a18O4Gtiff3gjB6OavAeJs/q
            1Clpu85d4HFaRel/XGAXamhuo6Cdbzoas80XIDJGuSZQglD+vQgLHsrgy5f9jVOx
            E5sqyQ+jxB7VDh71OKmANI0AEVjQVE5AeCOQ7CH8M0N2eUnbqNojEQobG8zEtCl2
            bz8A4kk8fQPADwOqW6GKVTCd0W/n7/eLTZ7JKsoRnFImfmqlc+ijYEu1awEwtIGY
            jPZ4m9x7WIjkxy1UXruWB+ugaM95x86YjXOBB04jIMqZ+LVSXIqypiFrjC8V/8eO
            Pc0gsJm9beJfjBtSWaB8Qr/S+GncRK+qieJIGyaNYV2/a63b+oZzJghwjfx+zn55
            bqAnchvjJMZL7mpWQkTO0m20ccB524ONOhy0aL1GWPixftcfK8zPjg8PRoUY/aDS
            XAGopujCLOXtF15MBjEFqLytzuxfZBbORS45O3bFqbIw4oHFsNiV1oZOtSd71ezj
            Xz0/+TZ7wqoby18ARRKh+tdbflmVce6pg+378+jcguwiZtBthCAScdd8OyYi
            =BEW0
            -----END PGP MESSAGE-----
          fp: E7D18B4BC10A415DC6CAC35D49050A20B365DB0D
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
