apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-prometheus-stack-seaweedfs
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: seaweedfs-storage
  resources:
    requests:
      storage: 50Gi
