apiVersion: garage.rajsingh.info/v1beta2
kind: GarageCluster
metadata:
  name: garage
  namespace: garage
spec:
  zone: home
  replication:
    factor: 3
  storage:
    replicas: 3
    metadata:
      size: 10Gi
      storageClassName: longhorn-double
    data:
      size: 500Gi
      storageClassName: longhorn-single
  network:
    rpcBindPort: 3901
    service:
      type: ClusterIP
  admin:
    adminTokenSecretRef:
      name: garage-admin-token
      key: admin-token
  layoutManagement:
    autoApply: true
  monitoring:
    enabled: true
