apiVersion: garage.rajsingh.info/v1beta1
kind: GarageReferenceGrant
metadata:
  name: baserow-grant
  namespace: baserow
spec:
  from:
    - kind: GarageBucket
      namespace: baserow
    - kind: GarageKey
      namespace: baserow
  to:
    - kind: GarageCluster
      name: garage
