apiVersion: garage.rajsingh.info/v1beta1
kind: GarageReferenceGrant
metadata:
  name: owncloud-grant
  namespace: garage
spec:
  from:
    - kind: GarageBucket
      namespace: owncloud
    - kind: GarageKey
      namespace: owncloud
  to:
    - kind: GarageCluster
      name: garage
