apiVersion: garage.rajsingh.info/v1beta1
kind: GarageReferenceGrant
metadata:
  name: baserow-grant
  namespace: garage
spec:
  from:
    - group: garage-rajsingh.info
      kind: GarageBucket
      namespace: baserow
    - group: garage.rajsingh.info
      kind: GarageKey
      namespace: baserow
  to:
    - group: garage.rajsingh-info
      kind: GarageCluster
      name: garage
