# apiVersion: traefik.io/v1alpha1
# kind: IngressRoute
# metadata:
#   name: romm-ingress
#   namespace: romm-app
# spec:
#   entryPoints:
#     - web
#   routes:
#     - match: Host(`roms.713602.xyz`)
#       kind: Rule
#       services:
#         - name: romm
#           port: 80
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: romm-ingress
  annotations:
    tailscale.com/funnel: "true"
  namespace: romm-app
spec:
  defaultBackend:
    service:
      name: romm
      port:
        number: 80
  ingressClassName: tailscale
  tls:
    - hosts:
        - romm
