apiVersion: v1
kind: Secret
metadata:
    name: romm-external-secret
    namespace: romm-app
type: Opaque
stringData:
    DB_USER: ENC[AES256_GCM,data:eMIzbw==,iv:oq9CwXGwEyxcoBcvwIq8Xvsh+TrPvLPUpqz7owLCvGs=,tag:QTPhOa7GesJdLBiMbIq1EA==,type:str]
    DB_PASSWD: ENC[AES256_GCM,data:9e8/GaZ4i+9kY8w=,iv:2V6AQfHWlISaOt/NH6dOasL4BEQkp1eR+nSbo0Q4Qxs=,tag:I7a+G2Jz3p4aT47WspaHKg==,type:str]
    DB_NAME: ENC[AES256_GCM,data:+KTJdA==,iv:/80/R3ZDVs53RpzAWLSbn34HvDfrtDAJVpMphEwO9GU=,tag:Pe+5C8BbfKVjjP6XpveClg==,type:str]
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:U4Sblout87Xi22xI+8eM,iv:kzpT6/+M63xHGOJrbXg0SKe3tRLgfB1OQn5NqiknSgE=,tag:n2+fa5D/3dDNsuu5DgCCkg==,type:str]
    DB_PORT: ENC[AES256_GCM,data:nf//GA==,iv:wV96he9T5khA9t0C0PuAqsrpWlPin7BwqOZzKL/ciLw=,tag:qy90cL0utPECra0V4UzaFQ==,type:str]
    ROMM_AUTH_SECRET_KEY: ENC[AES256_GCM,data:Aw8nmaYHTmkQFh3o3xHrVi4ugneZlYZWn8OEvbHu/8A=,iv:3iIoybGmALDInEs1E5VtpHqk+/n2TYS2LHmIV9s/PsI=,tag:kaGIlGwqmR6Cf8+SmNLOOw==,type:str]
    #ENC[AES256_GCM,data:e5CncgIXeG1bdkl+waVCQWhvnOUSxnQLv09D3yS4xK/i9bDiupby,iv:WTtw5OVdbxO+c7oh/7sygqvYbbyN2NpOZa+JAykHumM=,tag:vQXjMjtYrzGYaTiakTVKPw==,type:comment]
    #ENC[AES256_GCM,data:4D6Hshhird0/r8BmbvZFW0gx2M+HPbk6bruyIknPYpzFZQQ0Pl80OWLYliV5Ngw=,iv:Bj42UT4Zu/HX+OH4ixoVwkFt+DWm/jyOVvofO4Rtl38=,tag:XWRmQcm6UAMv6KUR+km3sQ==,type:comment]
    STEAMGRIDDB_API_KEY: ENC[AES256_GCM,data:lBo68PFbHYDwBaVGHjafXu5ts3lP7TM+XRnbbD0tHhM=,iv:i1ZJ3KSF4O1mPRR+yVKjY73EePmSYj0xEreaOwQ3xN0=,tag:aMpShDrJHWv5y2hRCRoELA==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-18T01:25:30Z"
    mac: ENC[AES256_GCM,data:2gWowpY94ruM5Tj7P4GrATxirHuMFec75NBw6Tbecywr50XVOQuN5z2ISwEuSKlQDGR15hZKgIw/mOkfUqOreDsV08s3cLMHqT7Hqm/hL6xMkwqolZIw0zIvDkxPUE5jpBgstgMGINbVMKG43MjPW52u+jaqHMyZCwuii0SFz7M=,iv:mOT1hGY4s6VThr4dIkZ/PUB9f0AEAOqb9FtM8Wzvr3I=,tag:JhnYY7qaiA2slxU9f46cog==,type:str]
    pgp:
        - created_at: "2026-05-18T01:21:50Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwQgRRSI4paOARAAz5cwnRUwyLpnSKEPeUwbZqMEc3yipkOun6o3niarZPJE
            eS6ICAQLd7W4TKhQtA93pLOVsWnKDUTEMo4rgleBzhugtYtbVDyOlmaBj8/ffvyG
            D/2RuokYHN4YZTrGFer+gxleZkhUjKceebfQzqpshuKG7pmcTl5D/7DpG0na/B6s
            RyIbWUbhZEWE2asLw48bKnmU23nAtxcUNjhbbqnC66tJbuTpbuhOr/ePzXbqOq3Y
            Wms/lTWBZBmMvST+Crjkbn7oNbZq5SeKMAuPsgUJdeWsuoCFDbrisv8iJ6mWXAVb
            mVfopRaDA49WOqO3N7IanJVWYbaPDItiZ1aLYvqIPRUN9NyR7yHcvZpUtvneaAMu
            Wgn2yYinZFdqTSZ8KD7cFsxzo8HB3H8GJ0K6JuYoYcq0t6Z9KY8OBDfdFPjCgN1/
            P6A1M8BWwsbgOkUXdiB18/h60Hms0G8+2icikMYXRooj+IiYo6ICgG0xl0DR6bnb
            H0Wv28SlVNHgunf8ox1JqFoT666W0ONpeYBI7tzmehjAL2yd0/+aZyvSff1A3dAO
            tZl7MjshWH8HK250hGvi6rgya4iUkcy7EW16pqGf2SvqP8zvyXizhVcdvQJUA2q9
            gDC5kh2ip76uctKMXMH3rZl7TmQrVMM07Aq4Z4ortR5tu9odUQMxpnAAyNvsnwjS
            XAEZpKAWTaTWriyKCJzd28AmfD237Y6fVcN0XhNjdtYxkx/GumSfwB0jMPgP4CwU
            YqSCd7GXg/z5GMxKTL5t6IsFU6utbm+Z0d6G4lUGVG+UASzmyGZwj2B0Hys1
            =CSHT
            -----END PGP MESSAGE-----
          fp: E7D18B4BC10A415DC6CAC35D49050A20B365DB0D
    version: 3.13.1
