apiVersion: garage.rajsingh.info/v1beta1
kind: GarageBucket
metadata:
  name: owncloud-bucket
  namespace: owncloud
spec:
  clusterRef:
    name: garage
    namespace: garage 
  quotas:
    maxSize: 100Gi
---
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageKey
metadata:
  name: owncloud-key
  namespace: owncloud
spec:
  clusterRef:
    name: garage
    namespace: garage
    
  bucketPermissions:
    - bucketRef:
        name: owncloud-bucket
      read: true
      write: true

  importKey:
    secretRef:
      name: s3-keys
