apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ocis-chart
  namespace: owncloud
spec:
  interval: 30m
  chart:
    spec:
      chart: charts/ocis
      version: '0.7.x'
      interval: 30m
      sourceRef:
        kind: GitRepository
        name: ocis-chart
        namespace: flux-system

  values:
    externalDomain: ocis.713602.xyz
    
    ingress:
      enabled : false

    insecure:
      oidcIdpInsecure: true
      ocisHttpApiInsecure: true

    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch   
 
    features:
      virusscan:
        enabled: true
      policies:
        enabled: false
      ocm:
        enabled: true

    secretRefs:
      s3CredentialsSecretRef: s3-key
 
    services:
      idm:
        persistence:
          enabled: true
          accessModes:
            - ReadWriteOnce
          storageClassName: longhorn-double
          size: 5Gi
      nats:
        persistence:
          enabled: true
          accessModes:
            - ReadWriteOnce
          storageClassName: longhorn-double
          size: 5Gi
      search:
        persistence:
          enabled: true
          accessModes:
            - ReadWriteOnce
          storageClassName: longhorn-double
          size: 5Gi
      storagesystem:
        persistence:
          enabled: true
          accessModes:
            - ReadWriteOnce
          storageClassName: longhorn-double
          size: 5Gi
      ocm:
        persistence:
          enabled: true
          accessModes:
            - ReadWriteOnce
          storageClassName: longhorn-double
          size: 5Gi
      storageusers:
        storageBackend:
          driver: s3ng
          driverConfig:
            s3ng:
              endpoint: "http://garage.garage.svc.cluster.local:80" 
              bucket: "owncloud-bucket"
              region: ""
        persistence:
          enabled: true
          accessModes:
            - ReadWriteOnce
          storageClassName: longhorn-single
          size: 100Gi

    monitoring:
      enabled: true
