apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ocis-chart
  namespace: owncloud
spec:
  interval: 30m
  chart:
    spec:
      chart: charts/ocis
      version: '0.7.x'
      interval: 30m
      sourceRef:
        kind: GitRepository
        name: ocis-chart
        namespace: flux-system

  values:
    externalDomain: ocis.713602.xyz
    
    ingress:
      enabled : false

    insecure:
      oidcIdpInsecure: true
      ocisHttpApiInsecure: true
    
    features:
      virusscan:
        enabled: true
      policies:
        enabled: false
      ocm:
        enabled: true
    
    storage:
      users:
        driver: s3ng
    
    config:
      storage:
        s3ng:
          endpoint: "http://garage.garage.svc.cluster.local:3900" 
          bucket: "owncloud-bucket"
          region: "home"
    secretRefs:
      s3credentialsSecretRef: s3-key
 
    services:
      idm:
        persistence:
          enabled: true
          accessModes:
            - ReadWriteOnce
      nats:
        persistence:
          enabled: true
          accessModes:
            - ReadWriteOnce
      search:
        persistence:
          enabled: true
          accessModes:
            - ReadWriteOnce
      storagesystem:
        persistence:
          enabled: true
          accessModes:
            - ReadWriteOnce
      ocm:
        persistence:
          enabled: true
          accessModes:
            - ReadWriteOnce
