apiVersion: v1
kind: Secret
metadata:
    name: s3-keys
    namespace: owncloud
type: Opaque
stringData:
    accessKey: ENC[AES256_GCM,data:/eeKowNrxfocu5dZVSyhxzNIDTpGX5bCaYy7ARXoSzQvrMfbpaHCTwI8idYnjYk1F5E=,iv:qhfByLbTirAGWNVRyeFO0xYDm+mOjjh6Xh//Zc8pLuU=,tag:PPi47IeHLQURG3uGMHn/5g==,type:str]
    secretKey: ENC[AES256_GCM,data:eUSAgG42vqzNVwZvdC8pMCMEvaxx3+BPi3frRhXKtT/vwbbGbTWkhLLL6Vg0aEzRY4vR2Phv+66rnj0idPXcpw==,iv:94SymaBJo+w9/tmYwb9eDJb6aRzFC+7ZYie0we9nXWE=,tag:XAeS/VAmhaTgnoh5c+CxBA==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-28T01:34:03Z"
    mac: ENC[AES256_GCM,data:rRQN2MIhduPUg/g3bpb38tv+rMvCLTDNNgXa19mp8fVYIbh0V6O7LU+saMaBF9EQTLSI2jB+DYqJFyeqgezAKlwi2lMhBaTiz7npXJ7Fb+laj9zJ1Bz+AvHL9WOYbdhuinrRw6kdYGplCRQNDzwpCaPVamAAJSp7VwxfYjXEAMY=,iv:IlA+fYs6C/EYUo4D3koE/7BKJhDxAR99bcmuzDndFxE=,tag:XsDoTIGeJohgAxqS4LWy5Q==,type:str]
    pgp:
        - created_at: "2026-06-02T02:04:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwQgRRSI4paOAQ/8CeEjf3ZdY7wGV8xWL18ofsH1mSk+Ony+fhnTF/gN4GGa
            UkpArwIohC06EFVob9ymQPiaWuhM69YxtbZ9fCQ0PQoSwUIKH2Wr+U0d0wIGfpDX
            OmqFqx6q6xwMgqk8QDvMxbYciGgfi2KKN2BtHfLg0xjhBPtKHsXc1GlMSsfFuse8
            WC+A/eUaeMEQvItb1aN/u28ifNNm0gjB2IZ2t24E9n4J7PlIiJYdopeMAxWw5bqn
            9BNZ653aEEzWrpkXHIwcFZA9XhgfMBRJ1ZS5oR6shVx3N3omP5AioDb6ya5/+yyF
            B+DDneeZGKMKLeA/qpHm28NjCHUG3gOM4FqJc3znlNteM5FfSQvD0Re3QP3srFyP
            e56FSo8sVlgxAT6vfCXYW3UvZXRxn36FiGzUt7M1xdzaehww++4M85G2WqESUbtx
            l6kjivFpj9YRNkoI9a8zOgOayjsqdyRGxml8dlHXWK/1IYxOFJLEl8qHDRyl0DAq
            /WNPduwFvc0OoKJfmn+Fgd1U1if7SLdTuLXp5E02fHvEYWbmvx5fiDprRAbo411U
            siIl1nkGkjuRMQU/CcCWcJoy62tj6gQY+Xjem75EbLhtQ6YSEK7oW6cJap46w+H4
            iZeh+0ypKLHiRcdgu+CVoLp3lBqrWJs+WjDEyRIQEx0mKR9yMyMZIIzX+DCK/ebS
            XgF84xtGqjD1LcfEMEX0qm3wIvvD/WHQlUZdVuQ6itg/30CXNs0Y1k+NcotIq+mP
            c3FBU+4sbZbB+M7d5czx1TBASRhxeUZwjxQEh/TN0IZVvBwgmNYLxzLYGK5rwtA=
            =Ul2L
            -----END PGP MESSAGE-----
          fp: E7D18B4BC10A415DC6CAC35D49050A20B365DB0D
    version: 3.13.1
