apiVersion: v1
kind: Secret
metadata:
    name: jwt-secret
    namespace: owncloud
type: Opaque
stringData:
    jwt-secret: ENC[AES256_GCM,data:nNS+SQRDIxqn9LtdxjwW8ilNloU7hszB4A4jT42xy7w=,iv:QS+UdziZNP7A7zJDA+So6RrTb2GIwInQFw+w9m+gZG0=,tag:YqHBNMY7txIjej5jgZwwFg==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T14:25:23Z"
    mac: ENC[AES256_GCM,data:XGSOTTmlpFy+EhYRN6oVJlfXqHrV4I0KhwE4toxLGTOLl3b9o+Icn7Bs7+JwNFXV8u0xKSea9/uUCbZdGxl+iWj0h0lYGoZzJfp1xtIm3zXXJ1Zv5XcS0OBJQC2pcKOkailpcNGzOBUmwsfGRCIlMpkuxvzhxBVfoFDggNXGIX4=,iv:R1qHn5bCxWEIqxp3An3mdmef7xCrjxhpvfF4hSN4FmA=,tag:xVO26IaYdvH0m6NzLfl9bw==,type:str]
    pgp:
        - created_at: "2026-06-29T13:31:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwQgRRSI4paOARAA4G6/P9Jo7ENWbvssorI/X3CmCsMukMOBPwstRXNSFMS7
            gN9QPBQ4wxikpedR/vFOH1R6bGTeeL5tnpShvfLX605SV0Er4Mg1SD/76uNr5958
            ADXmS8xa610UKiK0Po2bsaKbOXD9Cb09ihpOC3GdhfsHS8uquNFepjOMTB0SNaUw
            CwiFQAzbJmliRCSi673hmd/8EgsSG4a686hur7BH8obzYTjAOISrTf5eU37D2YS1
            zv2DMtjPyRNkSE2s2FduqDc8lak6JKhZ3ZtvOslG6C126VmNetkCRZZYuprDg85o
            YYDYnBDxXBMwiqGxAb7Q5uy/saqsynbILxC2xn7BxJYfAnfsiH+bQwG3Fu/S43WD
            4oPwKKeTt5lTMOUSuz6+MavYATr20jXI05VijxcJAYWq6oaSH34iLcxTSiOfgrpc
            2FQ2MLSvPsc03ELwkS2kTElox5RxU8TvdxMj28NN4jcSr/nJmVAdwR5lnpEx3WwD
            hK22amq0vR4J5V6MojREGidD71Yo5LrL/vOKXvviCmKio/W25VjE+9LQi7ip3xWZ
            c13O8g2lNqM6pZiis6QDRbjj+83zX1R80hktceFht692GP9hJbofKiITJ+A80dNs
            noy1rpkIL2vJaybTvHlNWuItfpko65eAUilCgQTho+dY6MTWYk6DCxPxet/iSBPS
            XgHKARpr98fybsPwwBUNaPphDDtHOZQ4BXLItvXWnISw9Tutcq2RNRJYtd36KF4t
            JLXuxITipobYWb86wRQs7JNxpZjUAkJj24u/RIxWCqP0s2aasqBQMr1ZzWrnVUM=
            =N2r7
            -----END PGP MESSAGE-----
          fp: E7D18B4BC10A415DC6CAC35D49050A20B365DB0D
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: machine-auth-api-key
    namespace: owncloud
type: Opaque
stringData:
    machine-auth-api-key: ENC[AES256_GCM,data:94qNXB7LmfLw1w0iIhbV5ThJA/2ia8tL1IFVeJ3S,iv:1c9k6e2MNrAS3PB7Jl1GbnSpupO/lYvsoz4Pu/RNq0s=,tag:4kHvYS0LGKzH+zL4hUMJKA==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T14:25:23Z"
    mac: ENC[AES256_GCM,data:XGSOTTmlpFy+EhYRN6oVJlfXqHrV4I0KhwE4toxLGTOLl3b9o+Icn7Bs7+JwNFXV8u0xKSea9/uUCbZdGxl+iWj0h0lYGoZzJfp1xtIm3zXXJ1Zv5XcS0OBJQC2pcKOkailpcNGzOBUmwsfGRCIlMpkuxvzhxBVfoFDggNXGIX4=,iv:R1qHn5bCxWEIqxp3An3mdmef7xCrjxhpvfF4hSN4FmA=,tag:xVO26IaYdvH0m6NzLfl9bw==,type:str]
    pgp:
        - created_at: "2026-06-29T13:31:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwQgRRSI4paOARAA4G6/P9Jo7ENWbvssorI/X3CmCsMukMOBPwstRXNSFMS7
            gN9QPBQ4wxikpedR/vFOH1R6bGTeeL5tnpShvfLX605SV0Er4Mg1SD/76uNr5958
            ADXmS8xa610UKiK0Po2bsaKbOXD9Cb09ihpOC3GdhfsHS8uquNFepjOMTB0SNaUw
            CwiFQAzbJmliRCSi673hmd/8EgsSG4a686hur7BH8obzYTjAOISrTf5eU37D2YS1
            zv2DMtjPyRNkSE2s2FduqDc8lak6JKhZ3ZtvOslG6C126VmNetkCRZZYuprDg85o
            YYDYnBDxXBMwiqGxAb7Q5uy/saqsynbILxC2xn7BxJYfAnfsiH+bQwG3Fu/S43WD
            4oPwKKeTt5lTMOUSuz6+MavYATr20jXI05VijxcJAYWq6oaSH34iLcxTSiOfgrpc
            2FQ2MLSvPsc03ELwkS2kTElox5RxU8TvdxMj28NN4jcSr/nJmVAdwR5lnpEx3WwD
            hK22amq0vR4J5V6MojREGidD71Yo5LrL/vOKXvviCmKio/W25VjE+9LQi7ip3xWZ
            c13O8g2lNqM6pZiis6QDRbjj+83zX1R80hktceFht692GP9hJbofKiITJ+A80dNs
            noy1rpkIL2vJaybTvHlNWuItfpko65eAUilCgQTho+dY6MTWYk6DCxPxet/iSBPS
            XgHKARpr98fybsPwwBUNaPphDDtHOZQ4BXLItvXWnISw9Tutcq2RNRJYtd36KF4t
            JLXuxITipobYWb86wRQs7JNxpZjUAkJj24u/RIxWCqP0s2aasqBQMr1ZzWrnVUM=
            =N2r7
            -----END PGP MESSAGE-----
          fp: E7D18B4BC10A415DC6CAC35D49050A20B365DB0D
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: storage-system-jwt-secret
    namespace: owncloud
type: Opaque
stringData:
    storage-system-jwt-secret: ENC[AES256_GCM,data:FHLFDze/580kmrRRIB2sCxYOwwz8u0G8rysFMpXSHMc=,iv:szU7jZXG4nngYTZUH02BaGvSSob8+LN3mzBuQYnzFD4=,tag:GO7uN1z8HNnm1dYRD8Kk5g==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T14:25:23Z"
    mac: ENC[AES256_GCM,data:XGSOTTmlpFy+EhYRN6oVJlfXqHrV4I0KhwE4toxLGTOLl3b9o+Icn7Bs7+JwNFXV8u0xKSea9/uUCbZdGxl+iWj0h0lYGoZzJfp1xtIm3zXXJ1Zv5XcS0OBJQC2pcKOkailpcNGzOBUmwsfGRCIlMpkuxvzhxBVfoFDggNXGIX4=,iv:R1qHn5bCxWEIqxp3An3mdmef7xCrjxhpvfF4hSN4FmA=,tag:xVO26IaYdvH0m6NzLfl9bw==,type:str]
    pgp:
        - created_at: "2026-06-29T13:31:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwQgRRSI4paOARAA4G6/P9Jo7ENWbvssorI/X3CmCsMukMOBPwstRXNSFMS7
            gN9QPBQ4wxikpedR/vFOH1R6bGTeeL5tnpShvfLX605SV0Er4Mg1SD/76uNr5958
            ADXmS8xa610UKiK0Po2bsaKbOXD9Cb09ihpOC3GdhfsHS8uquNFepjOMTB0SNaUw
            CwiFQAzbJmliRCSi673hmd/8EgsSG4a686hur7BH8obzYTjAOISrTf5eU37D2YS1
            zv2DMtjPyRNkSE2s2FduqDc8lak6JKhZ3ZtvOslG6C126VmNetkCRZZYuprDg85o
            YYDYnBDxXBMwiqGxAb7Q5uy/saqsynbILxC2xn7BxJYfAnfsiH+bQwG3Fu/S43WD
            4oPwKKeTt5lTMOUSuz6+MavYATr20jXI05VijxcJAYWq6oaSH34iLcxTSiOfgrpc
            2FQ2MLSvPsc03ELwkS2kTElox5RxU8TvdxMj28NN4jcSr/nJmVAdwR5lnpEx3WwD
            hK22amq0vR4J5V6MojREGidD71Yo5LrL/vOKXvviCmKio/W25VjE+9LQi7ip3xWZ
            c13O8g2lNqM6pZiis6QDRbjj+83zX1R80hktceFht692GP9hJbofKiITJ+A80dNs
            noy1rpkIL2vJaybTvHlNWuItfpko65eAUilCgQTho+dY6MTWYk6DCxPxet/iSBPS
            XgHKARpr98fybsPwwBUNaPphDDtHOZQ4BXLItvXWnISw9Tutcq2RNRJYtd36KF4t
            JLXuxITipobYWb86wRQs7JNxpZjUAkJj24u/RIxWCqP0s2aasqBQMr1ZzWrnVUM=
            =N2r7
            -----END PGP MESSAGE-----
          fp: E7D18B4BC10A415DC6CAC35D49050A20B365DB0D
    version: 3.13.1
