apiVersion: v1
kind: Secret
metadata:
    name: jwt-secret
    namespace: owncloud
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:sjTofeC25w==,iv:ALyb+X80tFatDFxKtC6ODOvqjyV/PkU5Ef4bM/a0cuo=,tag:OTKevvan4wwFJTOA2NerLw==,type:str]
    password: ENC[AES256_GCM,data:boHAU+Nj9J4TVhVIkqxRSiIB7XcFYD4fYoXbFFNdOHf2TjuOnoumRdLPzbxeGbEq,iv:mxcwpt/Vh9JlbY8ttJRSXMRNN6ijq/1g5G/9XTPIOHE=,tag:ItT1HHxF7D6xeiV2lDmS0g==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T14:18:11Z"
    mac: ENC[AES256_GCM,data:C/gzyClS9dImCKA0ZneQLt646QKCgBfDP6nWwiR3zk8TAo1ONX9+Bu8qdgmxxqy+n5nzrieTBHLuJb6+2E5pqkvarZt3Gjf4x0frMEY37rtkYT0Z/T3uJYDp+oVUBUCWxae8e3d5Nk5n/ohRl7zT4BCN47emHccAAGtEYn9yOH0=,iv:Zzb59Cf4rtk8m/eg+BRoWleLPUtG7WrrZ+Wm0+eDpkY=,tag:85AdJ7Jk9xzLxdps1NTkIw==,type:str]
    pgp:
        - created_at: "2026-06-29T13:31:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwQgRRSI4paOARAA4G6/P9Jo7ENWbvssorI/X3CmCsMukMOBPwstRXNSFMS7
            gN9QPBQ4wxikpedR/vFOH1R6bGTeeL5tnpShvfLX605SV0Er4Mg1SD/76uNr5958
            ADXmS8xa610UKiK0Po2bsaKbOXD9Cb09ihpOC3GdhfsHS8uquNFepjOMTB0SNaUw
            CwiFQAzbJmliRCSi673hmd/8EgsSG4a686hur7BH8obzYTjAOISrTf5eU37D2YS1
            zv2DMtjPyRNkSE2s2FduqDc8lak6JKhZ3ZtvOslG6C126VmNetkCRZZYuprDg85o
            YYDYnBDxXBMwiqGxAb7Q5uy/saqsynbILxC2xn7BxJYfAnfsiH+bQwG3Fu/S43WD
            4oPwKKeTt5lTMOUSuz6+MavYATr20jXI05VijxcJAYWq6oaSH34iLcxTSiOfgrpc
            2FQ2MLSvPsc03ELwkS2kTElox5RxU8TvdxMj28NN4jcSr/nJmVAdwR5lnpEx3WwD
            hK22amq0vR4J5V6MojREGidD71Yo5LrL/vOKXvviCmKio/W25VjE+9LQi7ip3xWZ
            c13O8g2lNqM6pZiis6QDRbjj+83zX1R80hktceFht692GP9hJbofKiITJ+A80dNs
            noy1rpkIL2vJaybTvHlNWuItfpko65eAUilCgQTho+dY6MTWYk6DCxPxet/iSBPS
            XgHKARpr98fybsPwwBUNaPphDDtHOZQ4BXLItvXWnISw9Tutcq2RNRJYtd36KF4t
            JLXuxITipobYWb86wRQs7JNxpZjUAkJj24u/RIxWCqP0s2aasqBQMr1ZzWrnVUM=
            =N2r7
            -----END PGP MESSAGE-----
          fp: E7D18B4BC10A415DC6CAC35D49050A20B365DB0D
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: machine-auth-api-key
    namespace: owncloud
type: kubernetes.io/basic-auth
stringData:
    machine-auth-api-key: ENC[AES256_GCM,data:94qNXB7LmfLw1w0iIhbV5ThJA/2ia8tL1IFVeJ3S,iv:1c9k6e2MNrAS3PB7Jl1GbnSpupO/lYvsoz4Pu/RNq0s=,tag:4kHvYS0LGKzH+zL4hUMJKA==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T14:18:11Z"
    mac: ENC[AES256_GCM,data:C/gzyClS9dImCKA0ZneQLt646QKCgBfDP6nWwiR3zk8TAo1ONX9+Bu8qdgmxxqy+n5nzrieTBHLuJb6+2E5pqkvarZt3Gjf4x0frMEY37rtkYT0Z/T3uJYDp+oVUBUCWxae8e3d5Nk5n/ohRl7zT4BCN47emHccAAGtEYn9yOH0=,iv:Zzb59Cf4rtk8m/eg+BRoWleLPUtG7WrrZ+Wm0+eDpkY=,tag:85AdJ7Jk9xzLxdps1NTkIw==,type:str]
    pgp:
        - created_at: "2026-06-29T13:31:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwQgRRSI4paOARAA4G6/P9Jo7ENWbvssorI/X3CmCsMukMOBPwstRXNSFMS7
            gN9QPBQ4wxikpedR/vFOH1R6bGTeeL5tnpShvfLX605SV0Er4Mg1SD/76uNr5958
            ADXmS8xa610UKiK0Po2bsaKbOXD9Cb09ihpOC3GdhfsHS8uquNFepjOMTB0SNaUw
            CwiFQAzbJmliRCSi673hmd/8EgsSG4a686hur7BH8obzYTjAOISrTf5eU37D2YS1
            zv2DMtjPyRNkSE2s2FduqDc8lak6JKhZ3ZtvOslG6C126VmNetkCRZZYuprDg85o
            YYDYnBDxXBMwiqGxAb7Q5uy/saqsynbILxC2xn7BxJYfAnfsiH+bQwG3Fu/S43WD
            4oPwKKeTt5lTMOUSuz6+MavYATr20jXI05VijxcJAYWq6oaSH34iLcxTSiOfgrpc
            2FQ2MLSvPsc03ELwkS2kTElox5RxU8TvdxMj28NN4jcSr/nJmVAdwR5lnpEx3WwD
            hK22amq0vR4J5V6MojREGidD71Yo5LrL/vOKXvviCmKio/W25VjE+9LQi7ip3xWZ
            c13O8g2lNqM6pZiis6QDRbjj+83zX1R80hktceFht692GP9hJbofKiITJ+A80dNs
            noy1rpkIL2vJaybTvHlNWuItfpko65eAUilCgQTho+dY6MTWYk6DCxPxet/iSBPS
            XgHKARpr98fybsPwwBUNaPphDDtHOZQ4BXLItvXWnISw9Tutcq2RNRJYtd36KF4t
            JLXuxITipobYWb86wRQs7JNxpZjUAkJj24u/RIxWCqP0s2aasqBQMr1ZzWrnVUM=
            =N2r7
            -----END PGP MESSAGE-----
          fp: E7D18B4BC10A415DC6CAC35D49050A20B365DB0D
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: storage-system-jwt-secret
    namespace: owncloud
type: kubernetes.io/basic-auth
stringData:
    storage-system-jwt-secret: ENC[AES256_GCM,data:FHLFDze/580kmrRRIB2sCxYOwwz8u0G8rysFMpXSHMc=,iv:szU7jZXG4nngYTZUH02BaGvSSob8+LN3mzBuQYnzFD4=,tag:GO7uN1z8HNnm1dYRD8Kk5g==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T14:18:11Z"
    mac: ENC[AES256_GCM,data:C/gzyClS9dImCKA0ZneQLt646QKCgBfDP6nWwiR3zk8TAo1ONX9+Bu8qdgmxxqy+n5nzrieTBHLuJb6+2E5pqkvarZt3Gjf4x0frMEY37rtkYT0Z/T3uJYDp+oVUBUCWxae8e3d5Nk5n/ohRl7zT4BCN47emHccAAGtEYn9yOH0=,iv:Zzb59Cf4rtk8m/eg+BRoWleLPUtG7WrrZ+Wm0+eDpkY=,tag:85AdJ7Jk9xzLxdps1NTkIw==,type:str]
    pgp:
        - created_at: "2026-06-29T13:31:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwQgRRSI4paOARAA4G6/P9Jo7ENWbvssorI/X3CmCsMukMOBPwstRXNSFMS7
            gN9QPBQ4wxikpedR/vFOH1R6bGTeeL5tnpShvfLX605SV0Er4Mg1SD/76uNr5958
            ADXmS8xa610UKiK0Po2bsaKbOXD9Cb09ihpOC3GdhfsHS8uquNFepjOMTB0SNaUw
            CwiFQAzbJmliRCSi673hmd/8EgsSG4a686hur7BH8obzYTjAOISrTf5eU37D2YS1
            zv2DMtjPyRNkSE2s2FduqDc8lak6JKhZ3ZtvOslG6C126VmNetkCRZZYuprDg85o
            YYDYnBDxXBMwiqGxAb7Q5uy/saqsynbILxC2xn7BxJYfAnfsiH+bQwG3Fu/S43WD
            4oPwKKeTt5lTMOUSuz6+MavYATr20jXI05VijxcJAYWq6oaSH34iLcxTSiOfgrpc
            2FQ2MLSvPsc03ELwkS2kTElox5RxU8TvdxMj28NN4jcSr/nJmVAdwR5lnpEx3WwD
            hK22amq0vR4J5V6MojREGidD71Yo5LrL/vOKXvviCmKio/W25VjE+9LQi7ip3xWZ
            c13O8g2lNqM6pZiis6QDRbjj+83zX1R80hktceFht692GP9hJbofKiITJ+A80dNs
            noy1rpkIL2vJaybTvHlNWuItfpko65eAUilCgQTho+dY6MTWYk6DCxPxet/iSBPS
            XgHKARpr98fybsPwwBUNaPphDDtHOZQ4BXLItvXWnISw9Tutcq2RNRJYtd36KF4t
            JLXuxITipobYWb86wRQs7JNxpZjUAkJj24u/RIxWCqP0s2aasqBQMr1ZzWrnVUM=
            =N2r7
            -----END PGP MESSAGE-----
          fp: E7D18B4BC10A415DC6CAC35D49050A20B365DB0D
    version: 3.13.1
