apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: baserow-ingress
  namespace: baserow
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`baserow.713602.xyz`)
      kind: Rule
      services:
        - name: baserow
          port: 80
