apiVersion: v1
kind: Secret
metadata:
    name: baserow-secrets
    namespace: baserow
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:Bj6iw+jpvQ==,iv:FS4fD660KRfEYXo4Hpk7jRcEhfYcjIQzPI8Cb7bCgJA=,tag:tRj7g2zIf6ZfnzSXeHKDCw==,type:str]
    password: ENC[AES256_GCM,data:d+Z99+SZU9lC,iv:aoVjgAJWZCBRl0AggqjbzXexVJddhpxQ+ZEb2Bpk3wk=,tag:MTe/CxFC2KcEyFGDnojITA==,type:str]
    DATABASE_USER: ENC[AES256_GCM,data:WYrIavpXGw==,iv:/ib5X/D2EUyX09LCCAeBda22fFeWVbezi8BtG3oAlkc=,tag:Z3OxkgDvCbXDR3IhkSJGfA==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:k6HxwSwq3Xdp,iv:daDI8GK/WWzeh5/SZO/eZuIi26aOi2HKGxB9xi1Ms/0=,tag:hTcd8XQPkqlRnXIp9O0+dA==,type:str]
    DATABASE_HOST: ENC[AES256_GCM,data:/qgFmr7vdVA2nJcgXxubWfRGZtqdGGYwuBUFKWO7ALiqPe0RMieF,iv:SIRTOy68yO3RLxcKQ12aSAAcViD6xB3Xn1xd1Dlk3EE=,tag:koRrMbtzSG7BcO4c4Fabfg==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:zkdmQD9ecUmMg9ak28IUrzvJ7bv3IuXWfmznh46weHSfINBXiBEV9Lb49XKIiEAzSOvr3DIrIAkPZJUj7vNqEypoz3pEPq8l6Wh1L6+dGBvu2reFaHWYHG49K9XcpNWngzmsDNclGBmUlODMAsV/k0OSQk7p,iv:cwCjDxIhJLIgmkNd51EM389i6DHYGmzxkSywR8LReVA=,tag:5II9n7w8tEb8SX2hbzRKxQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T04:25:41Z"
    mac: ENC[AES256_GCM,data:mhYqxXWeWNhMyhCQ2B2kkzbuQ713QzwL7z9UgkpQqQf499O170zXOCQjXhzILhZFnmAuaHkPxGFXJW9/1ySa6bK32JDZ35CuQ3VAoV8DXXBJmkZrnfwuC7+81zdTnoPT28EnEbGdGBuHMvEHzXkiZk4OBkaqf+Vy4YUdTc1uLsE=,iv:JcVl88DuNkVKOVe58+S1Fx8x/UsYkVLXSggaSb824LE=,tag:/VBpl8uaq5eSziplDkzuww==,type:str]
    pgp:
        - created_at: "2026-06-02T02:04:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwQgRRSI4paOAQ/8CeEjf3ZdY7wGV8xWL18ofsH1mSk+Ony+fhnTF/gN4GGa
            UkpArwIohC06EFVob9ymQPiaWuhM69YxtbZ9fCQ0PQoSwUIKH2Wr+U0d0wIGfpDX
            OmqFqx6q6xwMgqk8QDvMxbYciGgfi2KKN2BtHfLg0xjhBPtKHsXc1GlMSsfFuse8
            WC+A/eUaeMEQvItb1aN/u28ifNNm0gjB2IZ2t24E9n4J7PlIiJYdopeMAxWw5bqn
            9BNZ653aEEzWrpkXHIwcFZA9XhgfMBRJ1ZS5oR6shVx3N3omP5AioDb6ya5/+yyF
            B+DDneeZGKMKLeA/qpHm28NjCHUG3gOM4FqJc3znlNteM5FfSQvD0Re3QP3srFyP
            e56FSo8sVlgxAT6vfCXYW3UvZXRxn36FiGzUt7M1xdzaehww++4M85G2WqESUbtx
            l6kjivFpj9YRNkoI9a8zOgOayjsqdyRGxml8dlHXWK/1IYxOFJLEl8qHDRyl0DAq
            /WNPduwFvc0OoKJfmn+Fgd1U1if7SLdTuLXp5E02fHvEYWbmvx5fiDprRAbo411U
            siIl1nkGkjuRMQU/CcCWcJoy62tj6gQY+Xjem75EbLhtQ6YSEK7oW6cJap46w+H4
            iZeh+0ypKLHiRcdgu+CVoLp3lBqrWJs+WjDEyRIQEx0mKR9yMyMZIIzX+DCK/ebS
            XgF84xtGqjD1LcfEMEX0qm3wIvvD/WHQlUZdVuQ6itg/30CXNs0Y1k+NcotIq+mP
            c3FBU+4sbZbB+M7d5czx1TBASRhxeUZwjxQEh/TN0IZVvBwgmNYLxzLYGK5rwtA=
            =Ul2L
            -----END PGP MESSAGE-----
          fp: E7D18B4BC10A415DC6CAC35D49050A20B365DB0D
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: baserow-super-secrets
    namespace: baserow
type: kubernetes.io/basic-auth
stringData:
    password: ENC[AES256_GCM,data:5kZFZ7eJPS2x6NOmtnfgHJoPqWMm,iv:mvgGPNWovqegasHieO9qspQWG8TBYxc6l5aremSf3x8=,tag:Che7p8tBlVw8Rgs0K27Vww==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T04:25:41Z"
    mac: ENC[AES256_GCM,data:mhYqxXWeWNhMyhCQ2B2kkzbuQ713QzwL7z9UgkpQqQf499O170zXOCQjXhzILhZFnmAuaHkPxGFXJW9/1ySa6bK32JDZ35CuQ3VAoV8DXXBJmkZrnfwuC7+81zdTnoPT28EnEbGdGBuHMvEHzXkiZk4OBkaqf+Vy4YUdTc1uLsE=,iv:JcVl88DuNkVKOVe58+S1Fx8x/UsYkVLXSggaSb824LE=,tag:/VBpl8uaq5eSziplDkzuww==,type:str]
    pgp:
        - created_at: "2026-06-02T02:04:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwQgRRSI4paOAQ/8CeEjf3ZdY7wGV8xWL18ofsH1mSk+Ony+fhnTF/gN4GGa
            UkpArwIohC06EFVob9ymQPiaWuhM69YxtbZ9fCQ0PQoSwUIKH2Wr+U0d0wIGfpDX
            OmqFqx6q6xwMgqk8QDvMxbYciGgfi2KKN2BtHfLg0xjhBPtKHsXc1GlMSsfFuse8
            WC+A/eUaeMEQvItb1aN/u28ifNNm0gjB2IZ2t24E9n4J7PlIiJYdopeMAxWw5bqn
            9BNZ653aEEzWrpkXHIwcFZA9XhgfMBRJ1ZS5oR6shVx3N3omP5AioDb6ya5/+yyF
            B+DDneeZGKMKLeA/qpHm28NjCHUG3gOM4FqJc3znlNteM5FfSQvD0Re3QP3srFyP
            e56FSo8sVlgxAT6vfCXYW3UvZXRxn36FiGzUt7M1xdzaehww++4M85G2WqESUbtx
            l6kjivFpj9YRNkoI9a8zOgOayjsqdyRGxml8dlHXWK/1IYxOFJLEl8qHDRyl0DAq
            /WNPduwFvc0OoKJfmn+Fgd1U1if7SLdTuLXp5E02fHvEYWbmvx5fiDprRAbo411U
            siIl1nkGkjuRMQU/CcCWcJoy62tj6gQY+Xjem75EbLhtQ6YSEK7oW6cJap46w+H4
            iZeh+0ypKLHiRcdgu+CVoLp3lBqrWJs+WjDEyRIQEx0mKR9yMyMZIIzX+DCK/ebS
            XgF84xtGqjD1LcfEMEX0qm3wIvvD/WHQlUZdVuQ6itg/30CXNs0Y1k+NcotIq+mP
            c3FBU+4sbZbB+M7d5czx1TBASRhxeUZwjxQEh/TN0IZVvBwgmNYLxzLYGK5rwtA=
            =Ul2L
            -----END PGP MESSAGE-----
          fp: E7D18B4BC10A415DC6CAC35D49050A20B365DB0D
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: s3-keys
    namespace: baserow
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:pbq0GeuZR/d/uBQWLgAH604pAOvN8z1Cr7Jj4vZPvoxP591bguWFa2QhOUwdyONFGD8=,iv:Z04NLQoniRSkeosy0dS9IZtDKOZKH7BGRQRACIa5+nI=,tag:RtJ7+u/+JJMHD0VJTJM54A==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:M3iRhGmhKmh8wUQQ4kHWJ04ycBAIMaZfUcP6/R5P18B55KvdJke0q/90P9dz8hg0m0Aik8NpMPHm2OBk0NvEPQ==,iv:64DpXQ+kjz6F5OHztSCpc2OgM3Sbr/ZHyPChMGDm5AM=,tag:pFbVT7ATG3cGFvI9vLwoRA==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T04:25:41Z"
    mac: ENC[AES256_GCM,data:mhYqxXWeWNhMyhCQ2B2kkzbuQ713QzwL7z9UgkpQqQf499O170zXOCQjXhzILhZFnmAuaHkPxGFXJW9/1ySa6bK32JDZ35CuQ3VAoV8DXXBJmkZrnfwuC7+81zdTnoPT28EnEbGdGBuHMvEHzXkiZk4OBkaqf+Vy4YUdTc1uLsE=,iv:JcVl88DuNkVKOVe58+S1Fx8x/UsYkVLXSggaSb824LE=,tag:/VBpl8uaq5eSziplDkzuww==,type:str]
    pgp:
        - created_at: "2026-06-02T02:04:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwQgRRSI4paOAQ/8CeEjf3ZdY7wGV8xWL18ofsH1mSk+Ony+fhnTF/gN4GGa
            UkpArwIohC06EFVob9ymQPiaWuhM69YxtbZ9fCQ0PQoSwUIKH2Wr+U0d0wIGfpDX
            OmqFqx6q6xwMgqk8QDvMxbYciGgfi2KKN2BtHfLg0xjhBPtKHsXc1GlMSsfFuse8
            WC+A/eUaeMEQvItb1aN/u28ifNNm0gjB2IZ2t24E9n4J7PlIiJYdopeMAxWw5bqn
            9BNZ653aEEzWrpkXHIwcFZA9XhgfMBRJ1ZS5oR6shVx3N3omP5AioDb6ya5/+yyF
            B+DDneeZGKMKLeA/qpHm28NjCHUG3gOM4FqJc3znlNteM5FfSQvD0Re3QP3srFyP
            e56FSo8sVlgxAT6vfCXYW3UvZXRxn36FiGzUt7M1xdzaehww++4M85G2WqESUbtx
            l6kjivFpj9YRNkoI9a8zOgOayjsqdyRGxml8dlHXWK/1IYxOFJLEl8qHDRyl0DAq
            /WNPduwFvc0OoKJfmn+Fgd1U1if7SLdTuLXp5E02fHvEYWbmvx5fiDprRAbo411U
            siIl1nkGkjuRMQU/CcCWcJoy62tj6gQY+Xjem75EbLhtQ6YSEK7oW6cJap46w+H4
            iZeh+0ypKLHiRcdgu+CVoLp3lBqrWJs+WjDEyRIQEx0mKR9yMyMZIIzX+DCK/ebS
            XgF84xtGqjD1LcfEMEX0qm3wIvvD/WHQlUZdVuQ6itg/30CXNs0Y1k+NcotIq+mP
            c3FBU+4sbZbB+M7d5czx1TBASRhxeUZwjxQEh/TN0IZVvBwgmNYLxzLYGK5rwtA=
            =Ul2L
            -----END PGP MESSAGE-----
          fp: E7D18B4BC10A415DC6CAC35D49050A20B365DB0D
    version: 3.13.1
