apiVersion: v1
kind: Secret
metadata:
    name: baserow-secrets
    namespace: baserow
type: kubernetes.io/basic-auth
stringData:
    DATABASE_HOST: ENC[AES256_GCM,data:DQkQY5fn+233R416bofsQTuAzPPvVzJzpQl9iihwTuIUz8sSyw==,iv:p9kbequ/B32I+VHGNAAa32V4nicPWwVbsHyB7tImcyg=,tag:VBFftOLeh5e2YDJk6hW2/A==,type:str]
    DATABASE_PORT: ENC[AES256_GCM,data:ZK/kLQ==,iv:WMGZsLY+VXs8uuL4e5vfTvNIhDAZ3CpEn/R9+Tt3wMQ=,tag:YICeG9s3bVk8mnvJ3yNtXQ==,type:str]
    DATABASE_NAME: ENC[AES256_GCM,data:YsFzoL+d3Q==,iv:v6FcrXPnCIh0Led/+JxxvGkDwaobvDBY+1p06xk9nFc=,tag:8CM49sdZTkS7ovAz0SYWxA==,type:str]
    DATABASE_USER: ENC[AES256_GCM,data:q6dO8Sp5Rg==,iv:Yq8DbEZ45cSWY8NMoj3/400F1G2emDUiC/PlXUXpA6A=,tag:Nd1r8DHqpRVsboAaSsVk/w==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:Hc5ZyQyZ5wRjnGcIFv2OmBOlZtFG,iv:/PWLgiJMc41ed1OJMghW+G7zkrK74rT5nY4M4YSFJZM=,tag:AAQK7nYVGZ+HbjIhYWq4mg==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:EhxHc55OY353hziEQ68Hake89Kf6A3eLTP8/wR9CAKHJRrV3,iv:MDRoCP4/XWvO1uvt7r1LiPtIVt6GbXfXWhQ2F4fN/BM=,tag:V8eNLP5WSdP5sxJ9P0YXWw==,type:str]
    REDIS_PORT: ENC[AES256_GCM,data:cBygIA==,iv:LRMmWb1x9Is0ocR5FElQtvg7yfVkIgxYEKofiyKZuVE=,tag:kmQs/qpnbE9maP9j/8fxnQ==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:Gq6lPacCHgj7tljlkamlHw==,iv:BUk1n9LTBexbrQoWJpZBeAPM9V9oYDPseHUroa+9xKk=,tag:cO6bxVMAUSaNsnvaLrQqsw==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-02T02:04:15Z"
    mac: ENC[AES256_GCM,data:k18hfbeLktIgQ9AG9Nwhtaz078J7C9Uw5VsMG8a2g+ehor+daJZEFrNXTMK4Opt4/0cgnA6vbz0vdjtOf03/hDY5AV3DY1G5D0trXyYCfOS4HoBRjDz8OWC/FeFi3MbiBOiV/ghpl7eQFaGNhUylqVWvz1k1nYYGam0QO0aapzk=,iv:tS8Z2/pVjYBLue0gm10iZnIbj4l8g3Y+5ZTwqu/8tLM=,tag:i1Lnc0wYJiviXVrB/yMCDw==,type:str]
    pgp:
        - created_at: "2026-06-02T02:04:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwQgRRSI4paOAQ/8CeEjf3ZdY7wGV8xWL18ofsH1mSk+Ony+fhnTF/gN4GGa
            UkpArwIohC06EFVob9ymQPiaWuhM69YxtbZ9fCQ0PQoSwUIKH2Wr+U0d0wIGfpDX
            OmqFqx6q6xwMgqk8QDvMxbYciGgfi2KKN2BtHfLg0xjhBPtKHsXc1GlMSsfFuse8
            WC+A/eUaeMEQvItb1aN/u28ifNNm0gjB2IZ2t24E9n4J7PlIiJYdopeMAxWw5bqn
            9BNZ653aEEzWrpkXHIwcFZA9XhgfMBRJ1ZS5oR6shVx3N3omP5AioDb6ya5/+yyF
            B+DDneeZGKMKLeA/qpHm28NjCHUG3gOM4FqJc3znlNteM5FfSQvD0Re3QP3srFyP
            e56FSo8sVlgxAT6vfCXYW3UvZXRxn36FiGzUt7M1xdzaehww++4M85G2WqESUbtx
            l6kjivFpj9YRNkoI9a8zOgOayjsqdyRGxml8dlHXWK/1IYxOFJLEl8qHDRyl0DAq
            /WNPduwFvc0OoKJfmn+Fgd1U1if7SLdTuLXp5E02fHvEYWbmvx5fiDprRAbo411U
            siIl1nkGkjuRMQU/CcCWcJoy62tj6gQY+Xjem75EbLhtQ6YSEK7oW6cJap46w+H4
            iZeh+0ypKLHiRcdgu+CVoLp3lBqrWJs+WjDEyRIQEx0mKR9yMyMZIIzX+DCK/ebS
            XgF84xtGqjD1LcfEMEX0qm3wIvvD/WHQlUZdVuQ6itg/30CXNs0Y1k+NcotIq+mP
            c3FBU+4sbZbB+M7d5czx1TBASRhxeUZwjxQEh/TN0IZVvBwgmNYLxzLYGK5rwtA=
            =Ul2L
            -----END PGP MESSAGE-----
          fp: E7D18B4BC10A415DC6CAC35D49050A20B365DB0D
    version: 3.13.1
