# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-824e6098-7a3e-4da1-b51c-2b25c3f93b1a";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-824e6098-7a3e-4da1-b51c-2b25c3f93b1a".device = "/dev/disk/by-uuid/824e6098-7a3e-4da1-b51c-2b25c3f93b1a";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3D41-DEF3";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-c0f2f237-921c-40ca-b7de-6a97be77a458"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.npu.enable = true;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
