apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: garage
  namespace: garage
spec:
  interval: 30m
  chart:
    spec:
      chart: garage
      version: '0.6.x'
      sourceRef:
        kind: HelmRepository
        name: garage
        namespace: flux-system
      interval: 10m

  values:
    deployment:
      replicaCount: 3
    
    garage:
      replicationFactor: "2"
      secret:
        envFrom:
          - secretRef:
              name: garage-secrets
      s3:
        api:
          rootDomain: ".s3.homelab.prod"
        web:
          rootDomain: ".web.homelab.prod"
    
    persistence:
      enabled: true
      data:
        storageClass: garage-data-hdd
        size: 50Gi
      meta:
        storageClass: garage-meta-ssd
        size: 1Gi
    
    clusterConfig:
      enabled: true
      layout:
        enabled: true
        zone: home
      buckets:
        - name: backups
        - name: media
        - name: roms
        - name: docs
          public: true
      keys:
        my-key:
          envFrom:
            - secretRef:
                name: garage-secrets
#          keyId: GK0123456789ABCDEF01234567
#          secretKey: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
          buckets:
            - backups
            - media
            - roms
            - docs

    monitoring:
      metrics:
        enabled: true
      serviceMonitor:
        enabled: true
