apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: garage
  namespace: flux-system
spec:
  interval: 24h
  url: oci://ghcr.io/rajsinghtech/charts/garage-operator
  ref:
    semver: "0.6.x"
