apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 12h
  chartRef:
    kind: OCIRepository
    name: cert-manager
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    crds:
      enabled: true
      keep: true
    dns01RecursiveNameserversOnly: true
    dns01RecursiveNameservers: "8.8.8.8:53,1.1.1.1:53"

    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
