# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-c86544bd-4621-4fd5-b4d7-7ad99adcf912";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-c86544bd-4621-4fd5-b4d7-7ad99adcf912".device = "/dev/disk/by-uuid/c86544bd-4621-4fd5-b4d7-7ad99adcf912";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/50F0-76AC";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-aecb8201-43b8-40bd-912a-d40661b3ca26"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
